// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: q7hWdoDc5Fm3y1TqrPvEG7
// Component: NDD8Sm8rUkf
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_renai.module.css"; // plasmic-import: q7hWdoDc5Fm3y1TqrPvEG7/projectcss
import sty from "./PlasmicNavtxns.module.css"; // plasmic-import: NDD8Sm8rUkf/css
import TransactionsvgIcon from "./icons/PlasmicIcon__Transactionsvg"; // plasmic-import: lNMT-WL5B/icon

export const PlasmicNavtxns__VariantProps = new Array(
  "lbtoggle",
  "feedtoggle",
  "portfoliotoggle",
  "txntoggle",
  "proposaltoggle"
);

export const PlasmicNavtxns__ArgProps = new Array();

function PlasmicNavtxns__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return true ? (
    <p.Stack
      as={"button"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox___64FiG)}
      >
        <TransactionsvgIcon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(projectcss.all, sty.svg, {
            [sty.svgfeedtoggle]: hasVariant(
              variants,
              "feedtoggle",
              "feedtoggle"
            ),

            [sty.svglbtoggle]: hasVariant(variants, "lbtoggle", "lbtoggle"),
            [sty.svgportfoliotoggle]: hasVariant(
              variants,
              "portfoliotoggle",
              "portfoliotoggle"
            ),

            [sty.svgproposaltoggle]: hasVariant(
              variants,
              "proposaltoggle",
              "proposaltoggle"
            ),

            [sty.svgtxntoggle]: hasVariant(variants, "txntoggle", "txntoggle")
          })}
          role={"img"}
        />

        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text,
            {
              [sty.textfeedtoggle]: hasVariant(
                variants,
                "feedtoggle",
                "feedtoggle"
              ),

              [sty.textlbtoggle]: hasVariant(variants, "lbtoggle", "lbtoggle"),
              [sty.textportfoliotoggle]: hasVariant(
                variants,
                "portfoliotoggle",
                "portfoliotoggle"
              ),

              [sty.textproposaltoggle]: hasVariant(
                variants,
                "proposaltoggle",
                "proposaltoggle"
              ),

              [sty.texttxntoggle]: hasVariant(
                variants,
                "txntoggle",
                "txntoggle"
              )
            }
          )}
        >
          {"Transactions"}
        </div>
      </p.Stack>

      <div
        className={classNames(projectcss.all, sty.freeBox__ruPkO, {
          [sty.freeBoxfeedtoggle__ruPkOj0YeG]: hasVariant(
            variants,
            "feedtoggle",
            "feedtoggle"
          ),

          [sty.freeBoxlbtoggle__ruPkOr7Hei]: hasVariant(
            variants,
            "lbtoggle",
            "lbtoggle"
          ),

          [sty.freeBoxportfoliotoggle__ruPkOc6TqP]: hasVariant(
            variants,
            "portfoliotoggle",
            "portfoliotoggle"
          ),

          [sty.freeBoxproposaltoggle__ruPkOg0Bax]: hasVariant(
            variants,
            "proposaltoggle",
            "proposaltoggle"
          ),

          [sty.freeBoxtxntoggle__ruPkOjBzQp]: hasVariant(
            variants,
            "txntoggle",
            "txntoggle"
          )
        })}
      />
    </p.Stack>
  ) : null;
}

const PlasmicDescendants = {
  root: ["root", "svg", "text"],
  svg: ["svg"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNavtxns__ArgProps,
      internalVariantPropNames: PlasmicNavtxns__VariantProps
    });

    return PlasmicNavtxns__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavtxns";
  } else {
    func.displayName = `PlasmicNavtxns.${nodeName}`;
  }
  return func;
}

export const PlasmicNavtxns = Object.assign(
  // Top-level PlasmicNavtxns renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicNavtxns
    internalVariantProps: PlasmicNavtxns__VariantProps,
    internalArgProps: PlasmicNavtxns__ArgProps
  }
);

export default PlasmicNavtxns;
/* prettier-ignore-end */
