// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: q7hWdoDc5Fm3y1TqrPvEG7
// Component: tOZMt_Mp39
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Button2SignUpPage from "../../../Button2SignUpPage"; // plasmic-import: d6xbjF1TjG/component
import "@plasmicapp/react-web/lib/plasmic.css";
import sty from "./PlasmicFbplasmicbutton.module.css"; // plasmic-import: tOZMt_Mp39/css

export const PlasmicFbplasmicbutton__VariantProps = new Array();

export const PlasmicFbplasmicbutton__ArgProps = new Array();

function PlasmicFbplasmicbutton__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <Button2SignUpPage
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFbplasmicbutton__ArgProps,
      internalVariantPropNames: PlasmicFbplasmicbutton__VariantProps
    });

    return PlasmicFbplasmicbutton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFbplasmicbutton";
  } else {
    func.displayName = `PlasmicFbplasmicbutton.${nodeName}`;
  }
  return func;
}

export const PlasmicFbplasmicbutton = Object.assign(
  // Top-level PlasmicFbplasmicbutton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicFbplasmicbutton
    internalVariantProps: PlasmicFbplasmicbutton__VariantProps,
    internalArgProps: PlasmicFbplasmicbutton__ArgProps
  }
);

export default PlasmicFbplasmicbutton;
/* prettier-ignore-end */
