// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: q7hWdoDc5Fm3y1TqrPvEG7
// Component: 6B14PY8_QE
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_renai.module.css"; // plasmic-import: q7hWdoDc5Fm3y1TqrPvEG7/projectcss
import sty from "./PlasmicSwitchnetworkalert.module.css"; // plasmic-import: 6B14PY8_QE/css

export const PlasmicSwitchnetworkalert__VariantProps = new Array();

export const PlasmicSwitchnetworkalert__ArgProps = new Array();

function PlasmicSwitchnetworkalert__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.__wab_text,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {"Please switch to Polygon Testnet"}
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSwitchnetworkalert__ArgProps,
      internalVariantPropNames: PlasmicSwitchnetworkalert__VariantProps
    });

    return PlasmicSwitchnetworkalert__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSwitchnetworkalert";
  } else {
    func.displayName = `PlasmicSwitchnetworkalert.${nodeName}`;
  }
  return func;
}

export const PlasmicSwitchnetworkalert = Object.assign(
  // Top-level PlasmicSwitchnetworkalert renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicSwitchnetworkalert
    internalVariantProps: PlasmicSwitchnetworkalert__VariantProps,
    internalArgProps: PlasmicSwitchnetworkalert__ArgProps
  }
);

export default PlasmicSwitchnetworkalert;
/* prettier-ignore-end */
